// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStudent = "students"

// Student 学生表
type Student struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`               // 主键ID
	Name       string    `gorm:"column:name;not null;comment:名称" json:"name"`                                  // 名称
	Email      string    `gorm:"column:email;not null;comment:邮箱" json:"email"`                                // 邮箱
	Age        int32     `gorm:"column:age;not null;comment:年龄" json:"age"`                                    // 年龄
	Grade      int32     `gorm:"column:grade;not null;comment:年级编号" json:"grade"`                              // 年级编号
	Class      int32     `gorm:"column:class;not null;comment:班级编号" json:"class"`                              // 班级编号
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
