// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTeacherAndStudent = "teacher_and_students"

// TeacherAndStudent 老师学生表
type TeacherAndStudent struct {
	ID        int32 `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"` // 主键ID
	TeacherID int32 `gorm:"column:teacher_id;comment:教师ID" json:"teacher_id"`               // 教师ID
	StudentID int32 `gorm:"column:student_id;comment:学生ID" json:"student_id"`               // 学生ID
}

// TableName TeacherAndStudent's table name
func (*TeacherAndStudent) TableName() string {
	return TableNameTeacherAndStudent
}
